name: Test UI build for Renovate PRs

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Only run if the PR head branch starts with 'renovate-'
    if: startsWith(github.head_ref, 'renovate-')

    env:
      NODE_OPTIONS: --openssl-legacy-provider

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "yarn"
          cache-dependency-path: "ui/yarn.lock"

      - name: Set Yarn to v1 Classic
        run: yarn set version classic
        working-directory: ./ui

      - name: Check Node Version
        run: node --version
        working-directory: ./ui

      - name: Check Yarn Version
        run: yarn --version
        working-directory: ./ui

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./ui

      - name: Build application
        run: yarn build
        working-directory: ./ui
